/* eslint-disable react-refresh/only-export-components */
import {
  Children,
  cloneElement,
  createContext,
  isValidElement,
  useContext,
} from "react";

export const UI_LANGUAGE_STORAGE_KEY = "awplanet.interface-language";

const ZH_UI_TEXT = {
  "Project": "项目",
  "Character": "角色",
  "Objects": "物件",
  "Map": "地图",
  "Camera": "镜头",
  "Brush": "雕刻",
  "Detail panel": "详情面板",
  "Editor menus": "编辑器菜单",
  "Engine controls": "引擎工具",
  "Runtime modes": "导演模式",
  "Undo": "撤销",
  "Redo": "重做",
  "Obj": "物件",
  "Select": "选择",
  "Hide controls": "隐藏界面",
  "Show terrain controls": "显示界面",
  "Toggle object panel": "打开或关闭物件面板",
  "Toggle selection inspector": "打开或关闭选择面板",
  "Toggle terrain brush": "打开或关闭地形雕刻",
  "Toggle camera move": "切换镜头移动",
  "Sculpt tools": "雕刻工具",
  "Raise": "抬高",
  "Lower": "降低",
  "Smooth": "平滑",
  "Flatten": "压平",
  "Noise": "噪波",
  "Erode": "侵蚀",
  "Up": "抬高",
  "Low": "降低",
  "Soft": "平滑",
  "Flat": "压平",
  "Move": "移动",
  "Rotate": "旋转",
  "Scale": "缩放",
  "Save": "保存",
  "Load": "读取",
  "Reset": "重置",
  "Scene": "场景",
  "Previous scene": "上一个场景",
  "Next scene": "下一个场景",
  "Scene number": "场景序号",
  "Scene selector": "场景选择",
  "untitled scene": "未命名场景",
  "Play Mode": "游戏模式",
  "Pilot Mode": "飞行运镜",
  "Phone View": "手机虚拟拍摄",
  "Camera Pilot / FPV Dolly": "镜头飞手 / FPV 运镜",
  "Start play mode": "进入游戏模式",
  "Stop play mode": "退出游戏模式",
  "Start pilot mode": "进入飞行运镜",
  "Stop pilot mode": "退出飞行运镜",
  "Start phone pilot": "进入手机虚拟拍摄",
  "Stop phone pilot": "退出手机虚拟拍摄",
  "Play controls": "游戏操作",
  "Camera pilot controls": "飞行运镜操作",
  "Game camera modes": "游戏镜头模式",
  "View": "视角",
  "Elevate": "升降",
  "Speed": "速度",
  "WASD / Arrow Keys": "WASD / 方向键",
  "Hold Shift": "按住 Shift",
  "Mouse Drag / Wheel": "鼠标拖拽 / 滚轮",
  "Target": "目标",
  "Lock": "锁定",
  "Mouse Look": "鼠标视角",
  "Phone Online": "手机已连接",
  "Phone Armed": "手机待连接",
  "Phone Off": "手机关闭",
  "Third": "第三人称",
  "First": "第一人称",
  "Iso 45": "45° 等距",
  "Record Scene": "录制场景",
  "Stop Recording": "停止录制",
  "Saving Capture": "正在保存",
  "Start 60fps scene recording": "开始 60fps 场景录制",
  "Stop scene recording": "停止场景录制",
  "Record Take": "录制镜头",
  "Stop Take": "停止录制",
  "Saving Take": "正在保存",
  "Start pilot take recording": "开始录制飞行镜头",
  "Stop pilot take recording": "停止录制飞行镜头",
  "Video + Camera JSON": "视频 + 镜头 JSON",
  "Ready for 60fps capture.": "已准备好进行 60fps 录制。",
  "Use WASD to move.": "使用 WASD 移动。",
  "Play session started.": "游戏模式已启动。",
  "running": "运行中",
  "camera": "镜头",
  "online": "已连接",
  "waiting": "等待连接",
  "idle": "待机",
  "Copy": "复制",
  "Recenter": "重新校准",
  "Close": "关闭",
  "Move Scale": "移动映射",
  "Synced viewport connected": "同步画面已连接",
  "Open URL on phone": "在手机上打开地址",
  "scene link ready": "场景连接已就绪",
  "Project Name": "项目名称",
  "Project ready.": "项目已就绪。",
  "Current State": "当前状态",
  "New Project": "新建项目",
  "Blank Project": "空白项目",
  "Create a clean scene": "创建一个干净场景",
  "Open Project...": "打开项目...",
  "Recover Last Session": "恢复最近一次会话",
  "Recent Projects": "最近打开的项目",
  "No recent projects": "暂无最近项目",
  "Continue Editing": "继续编辑",
  "awplanet start": "awplanet 启动导航",
  "Save Project": "保存项目",
  "Load Project": "读取项目",
  "Scenes": "场景",
  "Add Scene": "新增场景",
  "Scene Outline": "场景结构",
  "Scene ID": "场景 ID",
  "Scene Index": "场景序号",
  "Runtime Values": "运行状态",
  "Identity": "基本信息",
  "Runtime": "运行状态",
  "Active Scene": "当前场景",
  "Camera Rig": "镜头控制",
  "select": "选择",
  "third-person": "第三人称",
  "character": "角色",
  "cinematic": "电影感",
  "History": "历史记录",
  "Selected": "当前选择",
  "Entities": "实体",
  "Type": "类型",
  "Position": "位置",
  "Material": "材质",
  "World": "世界",
  "Camera3D": "镜头",
  "CharacterBody3D": "角色",
  "MeshInstance3D": "网格物件",
  "Terrain3D": "地形",
  "LogicMarker": "逻辑标记",
  "Select a scene node": "请选择一个场景节点",
  "None": "无",
  "On": "开启",
  "Off": "关闭",
  "Character Follow": "角色跟随",
  "Eye View": "眼睛视角",
  "Diagonal Follow": "斜向跟随",
  "Cast": "角色列表",
  "Add Character": "增加角色",
  "Name": "名称",
  "Color": "颜色",
  "Stage Transform": "舞台变换",
  "Facing Angle": "朝向角度",
  "Ground Offset": "离地高度",
  "No Character": "无角色",
  "Bone Rig": "骨骼控制",
  "Rig On": "骨骼开启",
  "Rig Off": "骨骼关闭",
  "Expand bone rig": "展开骨骼控制",
  "Collapse bone rig": "收起骨骼控制",
  "Expand pose library": "展开姿势库",
  "Collapse pose library": "收起姿势库",
  "Selected Joint": "当前关节",
  "Move X": "移动 X",
  "Move Y": "移动 Y",
  "Move Z": "移动 Z",
  "Pose Name": "姿势名称",
  "Save Pose": "保存姿势",
  "Clear": "清除",
  "Pose Library": "姿势库",
  "Motion": "动作",
  "Static Poses": "静态姿势",
  "Custom Poses": "自定义姿势",
  "Walk": "行走",
  "Run": "奔跑",
  "Standard walking loop": "标准行走循环",
  "Running loop": "奔跑循环",
  "Saved custom bone pose": "已保存的自定义骨骼姿势",
  "Stand": "站立",
  "Relaxed": "放松站姿",
  "Sit": "坐姿",
  "Sit Lean": "倚靠坐姿",
  "Crouch": "蹲姿",
  "Jump Freeze": "腾空定格",
  "Landing": "落地姿势",
  "Dodge": "闪避",
  "Profile": "侧身",
  "Stop": "停止",
  "Neutral standing still": "自然站立",
  "Quiet standing pose": "放松静止站姿",
  "Seated static pose": "静态坐姿",
  "Seated candid frame": "自然倚靠坐姿",
  "Low body setup pose": "低位蹲姿",
  "Mid-air still pose": "腾空静态姿势",
  "Grounded landing pose": "稳定落地姿势",
  "Backward dodge still": "后向闪避姿势",
  "Turned body still": "侧身静态姿势",
  "Running stop still": "奔跑停止姿势",
  "Basic Objects": "基础物件",
  "Blender Primitives": "Blender 基础体",
  "Choose an object, then click the ground to place it.": "选择物件，然后点击地面进行放置。",
  "Cube": "立方体",
  "Sphere": "球体",
  "Cylinder": "圆柱体",
  "Cone": "圆锥体",
  "Plane": "平面",
  "Torus": "圆环",
  "All": "全部",
  "Terrain": "地形",
  "Houses": "建筑",
  "Interior": "室内",
  "City": "城市",
  "Devices": "装置",
  "Weathered Boulder": "风化巨石",
  "Desert Boulder": "沙漠巨石",
  "Moss Rock Set": "苔藓岩石组",
  "Loose Stone": "散落岩石",
  "Desert Stones": "沙漠石组",
  "Tree Stump": "树桩",
  "Gable House": "山墙房屋",
  "Balcony House": "阳台房屋",
  "Wide House": "宽型房屋",
  "Slim House": "窄型房屋",
  "Four Story Block": "四层建筑",
  "Bookshelf": "书架",
  "King Bed": "双人床",
  "Office Chair": "办公椅",
  "Desk": "书桌",
  "Sofa": "沙发",
  "Large Rock Platform": "大型岩石平台",
  "Tall Rock Platform": "高岩石平台",
  "Stepped Rock Platform": "阶梯岩石平台",
  "Grass Terrain Cube": "草地块",
  "Modular Bridge": "模块化桥梁",
  "Street Straight": "直线道路",
  "Street 4 Way": "四向道路",
  "Street Bridge": "道路桥",
  "Streetlight": "路灯",
  "Traffic Light": "交通灯",
  "Barrel": "木桶",
  "Crate": "货箱",
  "Chest": "宝箱",
  "Dungeon Arch": "地下城拱门",
  "Dungeon Column": "地下城立柱",
  "Hero Character": "主角模型",
  "World Material": "世界材质",
  "Material Settings": "材质设置",
  "Lighting": "光照",
  "Light Height": "光照高度",
  "Brightness": "亮度",
  "Light Angle": "水平角度",
  "Background": "背景",
  "Floor": "地面",
  "Blank": "空白",
  "Snow": "雪地",
  "Sand": "沙地",
  "Grass": "草地",
  "Water": "水面",
  "Stone": "岩石",
  "Backroom": "后室",
  "Room": "后室",
  "Relief": "起伏",
  "Roughness": "粗糙度",
  "Density": "密度",
  "Terrain Brush": "地形雕刻",
  "Brush Size": "笔刷大小",
  "Brush Strength": "笔刷强度",
  "Select a sculpt tool from the left dock. Move over the ground to preview the brush ring, then drag to sculpt.": "从左侧选择雕刻工具。移动到地面可预览笔刷圆环，按住拖拽进行雕刻。",
  "Editor Views": "编辑视角",
  "Perspective": "透视",
  "Top": "顶视",
  "Front": "前视",
  "Side": "侧视",
  "Target Node": "目标节点",
  "Follow Target": "跟随目标",
  "Lens And Frame": "镜头与构图",
  "View Distance": "镜头距离",
  "View Height": "镜头高度",
  "Head Forward": "头部前移",
  "Follow Smooth": "跟随平滑",
  "Lens FOV": "镜头焦距",
  "Live Shot Preview": "运镜预览",
  "Camera hero preview": "镜头运镜预览",
  "Preview": "预览",
  "Shot Presets": "运镜预设",
  "Neutral Chase": "中性跟随",
  "Over Shoulder": "越肩视角",
  "Fast Ground": "低位追随",
  "Readable World": "开阔跟随",
  "Head Camera": "头部镜头",
  "45 Degree": "45° 视角",
  "RPG Map": "RPG 俯视",
  "Circular Move": "环绕运动",
  "Slow Push": "缓慢推进",
  "Vertical Arc": "垂直弧线",
  "Human Motion": "手持运动",
  "Hitchcock": "希区柯克变焦",
  "Reverse": "反向运动",
  "Unease": "不安视角",
  "Emphasis": "强调推进",
  "Reveal Scale": "尺度揭示",
  "Side Travel": "侧向移动",
  "Foreground Sweep": "前景扫过",
  "Rise Reveal": "上升揭示",
  "Fast Reframe": "快速重构图",
  "Long Lens": "长焦视角",
  "Actor Locked": "角色锁定",
  "Focus Pulse": "焦点呼吸",
  "Follow Tuning": "跟随调节",
  "Target Follow": "目标跟随",
  "Preset Motion": "预设运动",
  "Loop Playback": "循环播放",
  "Once": "单次",
  "Loop": "循环",
  "Import Shot File": "导入镜头文件",
  "Preset File": "预设文件",
  "Template JSON": "模板 JSON",
  "Clear Imported": "清除导入",
  "Inspect": "检查",
  "Distance": "距离",
  "Locked": "锁定",
  "Orbit": "环绕",
  "Dolly": "轨道",
  "Vertigo": "希区柯克变焦",
  "Push": "推进",
  "Pull": "拉远",
  "Truck": "横移",
  "Arc": "弧线",
  "Crane": "摇臂",
  "Boom": "升降",
  "Pan": "摇镜",
  "Dutch": "荷兰角",
  "Pulse": "脉冲",
  "Continuous camera move": "连续循环运镜",
  "Select another shot preset to switch movement style. Sliders below tune this preset.": "选择其他运镜预设以切换运动方式，下方滑块用于微调当前预设。",
  "Free 3D": "自由 3D",
  "Plan View": "平面视图",
  "Elevation": "立面视图",
  "Orthographic Side": "正交侧视",
  "Click the camera button beside this panel to move the editor view.": "点击面板左侧的镜头按钮后，可移动编辑视角。",
  "Import a JSON file or ES module with one shot preset or an array.": "导入包含单个或多个镜头预设的 JSON、JS 或 MJS 文件。",
  "Pilot Speed": "飞行速度",
  "Look Speed": "转向速度",
  "Look Ease": "转向缓动",
  "Pilot Smooth": "飞行平滑",
  "Input Lag": "输入缓冲",
  "Swing Amount": "摆动幅度",
  "Pilot FOV": "飞行焦距",
  "Pilot Roll": "飞行横滚",
  "Hero Follow": "主角跟随",
  "Shoulder": "越肩",
  "Low Chase": "低位跟随",
  "High Chase": "高位跟随",
  "Eye Forward": "眼前视角",
  "Tactical View": "战术视角",
  "Top Down": "俯视",
  "Side Follow": "侧向跟随",
  "Orbit Reveal": "环绕揭示",
  "Dolly Push": "轨道推进",
  "Crane Drift": "摇臂漂移",
  "Handheld": "手持",
  "Vertigo Pull": "希区柯克拉远",
  "Vertigo Push": "希区柯克推进",
  "Dutch Tilt": "荷兰角",
  "Push In": "推进",
  "Pull Out": "拉远",
  "Truck Left": "横移",
  "Parallax Arc": "视差环绕",
  "Boom Up": "升降上移",
  "Whip Pan": "甩镜",
  "Surveillance": "监控视角",
  "Snorri Lock": "固定机位",
  "Lens Breath": "镜头呼吸",
  "Target Lead": "目标预留",
  "Side Offset": "侧向偏移",
  "Pitch Bias": "俯仰偏移",
  "Move Amount": "运动幅度",
  "Move Speed": "运动速度",
  "Phase": "运动相位",
  "FOV Swing": "焦距变化",
  "Roll": "横滚",
  "Frame X": "构图 X",
  "Frame Y": "构图 Y",
  "Storyboard Timeline": "分镜时间轴",
  "Storyboard timeline": "分镜时间轴",
  "Toggle storyboard timeline": "打开或关闭分镜时间轴",
  "Play": "播放",
  "Pause": "暂停",
  "Record": "录制",
  "Export": "导出",
  "Cancel Export": "取消导出",
  "Export timeline video": "导出时间轴视频",
  "Cancel timeline export": "取消时间轴导出",
  "Timeline ready.": "时间轴已就绪。",
  "Camera Pilot": "飞行运镜",
  "Drag inside the viewport to steer the lens while Hero keeps performing.": "在画面中拖拽控制镜头，角色会继续当前动作。",
};

const UiLanguageContext = createContext("en");

export const UiLanguageProvider = UiLanguageContext.Provider;
export const useUiLanguage = () => useContext(UiLanguageContext);

export const translateUiText = (value, language = "en") => {
  if (language !== "zh" || typeof value !== "string") return value;
  if (ZH_UI_TEXT[value]) return ZH_UI_TEXT[value];

  let match = value.match(/^(\d+) tracks · (\d+) clips$/);
  if (match) return `${match[1]} 条轨道 · ${match[2]} 个片段`;

  match = value.match(/^(\d+) entities$/);
  if (match) return `${match[1]} 个实体`;

  match = value.match(/^(\d+) clips$/);
  if (match) return `${match[1]} 个片段`;

  match = value.match(/^(\d+) nodes$/);
  if (match) return `${match[1]} 个节点`;

  match = value.match(/^(\d+) undo \/ (\d+) redo$/);
  if (match) return `${match[1]} 次撤销 / ${match[2]} 次重做`;

  match = value.match(/^Material · (.+)$/);
  if (match) return `材质 · ${translateUiText(match[1], language)}`;

  match = value.match(/^Sculpt (.+)$/);
  if (match) return `雕刻：${translateUiText(match[1], language)}`;

  match = value.match(/^Click the ground to place (.+)\.$/);
  if (match) return `点击地面放置${translateUiText(match[1], language)}。`;

  match = value.match(/^(\d+) custom$/);
  if (match) return `${match[1]} 个自定义预设`;

  if (value.includes(" · ")) {
    return value
      .split(" · ")
      .map((part) => translateUiText(part, language))
      .join(" · ");
  }

  return value;
};

export const localizeUiTree = (node, language) => {
  if (language !== "zh") return node;
  if (typeof node === "string") return translateUiText(node, language);
  if (!isValidElement(node)) return node;
  if (node.props?.["data-no-localize"]) return node;

  const translatedProps = {};
  ["aria-label", "title", "placeholder", "alt"].forEach((property) => {
    if (typeof node.props?.[property] === "string") {
      translatedProps[property] = translateUiText(node.props[property], language);
    }
  });

  if (Object.prototype.hasOwnProperty.call(node.props ?? {}, "children")) {
    translatedProps.children = Children.map(node.props.children, (child) =>
      localizeUiTree(child, language)
    );
  }

  return cloneElement(node, translatedProps);
};
