export const ENGINE_CAPABILITIES = {
  engine: "ai-native-three-runtime",
  version: "0.1.0",
  intent: "Codex and API clients should call structured engine commands instead of generating ad hoc Three.js scenes.",
  commands: [
    {
      type: "set-editor-tool",
      label: "Set Editor Tool",
      description: "Select the active editor tool and its secondary settings.",
      args: {
        tool: ["select", "object-placement", "brush", "camera-move"],
        selectedAssetKey: "optional object asset key",
        brushMode: ["raise", "lower"],
        brushSize: "number",
        brushStrength: "number",
      },
    },
    {
      type: "switch-terrain",
      label: "Switch Terrain",
      description: "Switch the active scene terrain material/environment.",
      args: {
        terrainId: ["blank", "snow", "sand", "grass", "water"],
      },
    },
    {
      type: "set-terrain-parameter",
      label: "Set Terrain Parameter",
      description: "Adjust one parameter on the active terrain preset.",
      args: {
        terrainId: "string",
        parameter: ["relief", "roughness", "density"],
        value: "number",
      },
    },
    {
      type: "sculpt-terrain",
      label: "Sculpt Terrain",
      description: "Apply a circular terrain raise/lower stamp to the active sculptable terrain.",
      args: {
        terrainId: ["blank", "snow", "sand", "grass"],
        point: "[x, y, z]",
        mode: ["raise", "lower"],
        size: "number",
        strength: "number",
      },
    },
    {
      type: "set-project-property",
      label: "Set Project Property",
      description: "Patch an editable property on the active project document.",
      args: {
        property: ["name"],
        value: "string | number | boolean",
      },
    },
    {
      type: "set-scene-property",
      label: "Set Scene Property",
      description: "Patch an editable property on the active scene document.",
      args: {
        property: ["name", "backgroundColor", "floorColor", "terrainFloorColors"],
        value: "string | number | boolean",
      },
    },
    {
      type: "set-camera-property",
      label: "Set Camera Property",
      description: "Patch an editable property on the active Camera3D node.",
      args: {
        property: "string",
        value: "string | number | [x, y, z]",
      },
    },
    {
      type: "set-camera-preset",
      label: "Set Camera Preset",
      description: "Apply a named Camera3D interaction/framing preset.",
      args: {
        preset: [
          "hero-follow",
          "shoulder",
          "low-chase",
          "high-chase",
          "eye-forward",
          "iso-tactical",
          "top-down",
          "side-follow",
          "orbit-reveal",
          "dolly-push",
          "crane-drift",
          "handheld",
          "vertigo-pull",
          "vertigo-push",
          "dutch-tension",
          "push-in",
          "pull-out",
          "truck-left",
          "parallax-arc",
          "boom-up",
          "whip-pan",
          "surveillance",
          "snorri-lock",
          "lens-breathe",
        ],
        camera: {
          mode: ["third-person", "first-person", "isometric", "orbit"],
          targetEntityId: "entity id",
          followDistance: "number",
          followHeight: "number",
          targetLead: "number",
          motionType: [
            "none",
            "orbit",
            "dolly",
            "vertigo",
            "push",
            "pull",
            "truck",
            "arc",
            "crane",
            "boom",
            "pan",
            "dutch",
            "pulse",
            "handheld",
          ],
          motionLoop: "boolean",
          motionAmplitude: "number",
          motionSpeed: "number",
          fovSwing: "number",
          cameraRoll: "number",
          compositionX: "number",
          compositionY: "number",
          pilotLookSpeed: "number",
          pilotLookSmoothing: "number",
          pilotSpeed: "number",
          pilotElevationSpeed: "number",
          pilotSmoothing: "number",
          pilotInputLag: "number",
          pilotSwingAmount: "number",
          pilotFov: "number",
          pilotRoll: "number",
          pilotLockTargetEnabled: "boolean",
          pilotLockTargetEntityId: "entity id",
          phonePilotEnabled: "boolean",
          phonePilotLookAmount: "number",
          phonePilotPitchAmount: "number",
          phonePilotRollAmount: "number",
          phonePilotSmoothing: "number",
          phonePilotMoveScale: "number",
          phonePilotHeightAmount: "number",
          position: "[x, y, z]",
          target: "[x, y, z]",
          minDistance: "number",
          maxDistance: "number",
        },
      },
    },
    {
      type: "start-play-session",
      label: "Start Play Session",
      description: "Enter runtime play mode, spawn the hero at the best available start marker, and initialize RPG progress tracking.",
      args: {},
    },
    {
      type: "stop-play-session",
      label: "Stop Play Session",
      description: "Exit runtime play mode and return to editing.",
      args: {},
    },
    {
      type: "set-hero-runtime-transform",
      label: "Set Hero Runtime Transform",
      description: "Move the playable hero during runtime without adding undo history.",
      args: {
        position: "[x, y, z]",
        rotation: "[x, y, z]",
        locomotionState: [
          "idle",
          "walkForward",
          "walkBack",
          "walkLeft",
          "walkRight",
          "runForward",
          "runBack",
          "runLeft",
          "runRight",
        ],
      },
    },
    {
      type: "collect-gameplay-marker",
      label: "Collect Gameplay Marker",
      description: "Trigger RPG marker progress such as treasure, encounter, objective, or exit completion.",
      args: {
        entityId: "marker entity id",
      },
    },
    {
      type: "generate-map",
      label: "Generate Map",
      description: "Generate a procedural office layout or maze.",
      args: {
        preset: ["rpg-rooms", "maze"],
        seed: "optional string | number for reproducible generation",
        config: {
          "rpg-rooms": [
            "footprintWidth",
            "footprintDepth",
            "bedrooms",
            "bathrooms",
            "openPlan",
            "entryInset",
            "wallHeight",
            "encounterDensity",
            "lootRooms",
          ],
          maze: [
            "size",
            "extraOpenings",
            "wallHeight",
            "wallColorMix",
            "encounterDensity",
            "treasureRooms",
          ],
        },
      },
    },
    {
      type: "generate-osm-map",
      label: "Import OSM Map",
      description: "Convert GeoJSON or Overpass OSM JSON into generated roads, buildings, water, green areas, markers, and colliders.",
      args: {
        data: "GeoJSON FeatureCollection | Overpass JSON",
        label: "optional scene label",
        seed: "optional stable import seed",
        config: ["worldScale", "roadWidthScale", "buildingHeightScale", "waterLevel"],
      },
    },
    {
      type: "add-entity",
      label: "Add Entity",
      description: "Spawn an asset from the engine asset registry into the active scene.",
      args: {
        id: "optional stable entity id",
        assetKey: "registered asset key",
        position: "[x, y, z]",
      },
    },
    {
      type: "select-entity",
      label: "Select Entity",
      description: "Select an entity for inspector/edit operations.",
      args: {
        entityId: "string | null",
      },
    },
    {
      type: "transform-entity",
      label: "Transform Entity",
      description: "Patch transform fields on an existing entity.",
      args: {
        entityId: "string",
        patch: {
          position: "[x, y, z]",
          rotation: "[x, y, z]",
          scale: "[x, y, z]",
        },
      },
    },
    {
      type: "set-entity-property",
      label: "Set Entity Property",
      description: "Patch an editable property on an existing entity.",
      args: {
        entityId: "string",
        property: [
          "label",
          "color",
          "groundOffset",
          "locomotionState",
          "collisionEnabled",
          "boneRigEnabled",
          "boneRigTransformMode",
          "selectedBoneJointId",
          "selectedBoneName",
          "boneOverrides",
          "boneMoveOverrides",
          "boneMoveProfiles",
          "customPoses",
        ],
        value: "string | number | [x, y, z] | object",
      },
    },
    {
      type: "delete-selected",
      label: "Delete Selected",
      description: "Delete the selected non-hero entity.",
      args: {},
    },
    {
      type: "run-command-batch",
      label: "Run Command Batch",
      description: "Execute a list of commands as one undoable transaction.",
      args: {
        label: "string",
        commands: "Array<engine command>",
      },
    },
    {
      type: "undo",
      label: "Undo",
      description: "Revert the previous undoable engine transaction.",
      args: {},
    },
    {
      type: "redo",
      label: "Redo",
      description: "Reapply the next reverted engine transaction.",
      args: {},
    },
  ],
  assetPipeline: {
    importers: [
      "character-fbx",
      "gltf-prop",
    ],
    validation: [
      "meshCount",
      "skinnedMeshCount",
      "boneCount",
      "animationCount",
      "materialCount",
      "textureCount",
      "warnings",
      "errors",
    ],
  },
};

export const getEngineCapabilities = () => ENGINE_CAPABILITIES;
